"""Utility constants and functions for the tetris game."""

NUM_ROWS = 25
NUM_COLS = 12
BOX_WIDTH = 20
CANVAS_WIDTH = BOX_WIDTH * NUM_COLS
CANVAS_HEIGHT = BOX_WIDTH * NUM_ROWS
SCREEN_WIDTH = 2 * CANVAS_WIDTH
SCREEN_HEIGHT = CANVAS_HEIGHT + 22
DEFAULT_TIME_STEP = 300
TIME_STEP_REDUCE = 0.9995
MIN_TIME_STEP = 200
SAVED_STATE_NAME = 'save'

